# docker-compose.yml

version: '3'
services:
  backend:
    image: mybatis-parser-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mybatis-parser-mysql/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    volumes:
      - /Volumes/T7/Project/SR/2023-11-01:/app/data
    depends_on:
      - mybatis-parser-mysql

  mybatis-parser-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"

  frontend:
    image: mybatis-parser-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
