spring:
  datasource:
    url:
    driverClassName: com.mysql.cj.jdbc.Driver
    username:
    password:

# JPA settings
  jpa :
    database-platform : org.hibernate.dialect.MySQL57Dialect
    show-sql : true
    hibernate:
      ddl-auto: create

external:
  folder-path: /app/data # EXTERNAL_FOLDER_PATH=/app/data 경로 설정 안될 경우 동작
