# Use a lightweight Nginx image
FROM nginx:alpine

# Set the working directory
WORKDIR /etc/nginx

# Remove default configuration
RUN rm -f nginx.conf

# Copy custom nginx.conf
COPY nginx.conf /etc/nginx/

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
